### ISSUE TITLE
Consider alternate semantics to .chainEnd()

### ISSUE THREAD

**Issue by justsml** [functional-promises/functional-promises#35]
## Consider alternatives to [`.chain()` / `.chainEnd()`](http://www.fpromises.io/#fp-chain-chainend)

> See [details and examples for current chaining API](http://www.fpromises.io/#fp-chain-chainend)

### Outline of changes

1. Instead of `.chain()` consider: `.build()`, `.create()`, `.record()`, or `.pipeline()`
1. Instead of limiting to `.chainEnd()`:
    * `.toPromise()` returns a function which runs the Chain of functions, returning the final result as a promise.
    * `.toCallback()(err, value)`
    * `.toListener(object, events)`

### Avoid Semver Major +1

* Alias `.chainEnd` to `.toPromise()`
* Alias `.chain()` w/ `.build()`

```js
const loud = value => (''+ value).toUpperCase()

const chainFn = FP.build()
    .then(loud)
    .tap(console.log)
    .then(s => s + '!!!')
    .toPromise()

chainFn('dan levy')
  .then(s => console.log(`Hi ${s}`)) // Hi DAN LEVY!!!


const callbackFn = FP.chain()
  .then(loud)
  .toCallback()

callbackFn('dan levy', (err, upperStr) => {
  console.log(`Hello ${upperStr}`) //=> Hello DAN LEVY
})

const listenFn = FP.chain()
  .get('target')
  .get('textContent')
  .then(loud)
  .tap(str => console.log('Loud: ' + str))
  .toListener()

listenFn(statusFooter, 'click', 'mouseover')
```

**Comment by BrooksPatton** [comment]
I recommend toPromise, it makes the most sense to me.
