### ISSUE TITLE
error in findIndex example from site

### ISSUE THREAD

**Issue by Gi972** [functional-promises/functional-promises#48]
Hello,

I try this example on your site
but the findIndex return only 0 (normally here he should return 3)

```
const rawData = [-99, null, undefined, NaN, 0, 20,40,50,'99']

// Async compatible (not needed in this simple example)
FP.resolve(rawData)
  .filter(x => x)         // truthiness check = [-99, "99"]
  .map(x => parseInt(x))  // convert to numeric [-99 99]
  .findIndex(n => n == 50) // is gte 1, idx = 1
  .then(index => {
    console.log(index)    // 0
  })
```

Thanks

**Comment by Gi972** [comment]
Otherwise, are you sure on the initial example the result of comment is 0 , I think the return of index was 1

**Comment by justsml** [comment]
Good spotting - there's a bug in how findIndex tracks the index of matches.

Research/WIP: https://runkit.com/justsml/fp-findindex

**Comment by justsml** [comment]
Note: I removed the .findIndex from the docs so it's de-emphasized to users until I can decide on a resolution.
