### ISSUE TITLE
extended get method

### ISSUE THREAD

**Issue by Gi972** [functional-promises/functional-promises#55]
just a suggestion,

like this https://30secondsofcode.org/object#get
the get method,

it's possible to pass a string like get('target.value')
 
instead of
get('target').get('value')

except if it is a will from you.

**Comment by justsml** [comment]
Thanks @Gi972 - this is a great idea.

I'm worried about 'scope creep' - will it support array specifiers? The complexity can get a little crazy...

There's probably a way to use something modular like: https://lodash.com/docs/#get

**Comment by justsml** [comment]
Posting some updates on this front:

## Now supported

* pluck multiple keys. 
* static utility method.

### Pluck multiple keys

Using an array (or arg list) of key names:

```js
FP.resolve({id: 42, email: 'e@mail', created: '-3d'})
  .get('id', 'email')
// Result: {id: 42, email: 'e@mail'}
```

### Static utility method
```js
const idAndEmailExtractor = FP.get('id', 'email')

idAndEmailExtractor({id: 42, email: 'e@mail', created: '-3d'})
// Result: {id: 42, email: 'e@mail'}
```
> This is very handy in many parts of JS: Plain-ol-JS-Objects, Array Methods, Promise Chains.

```js
// Named helper/utility function:
const emailGetter = FP.get('email')
const emailsList = users.map(emailGetter)

// Inline w/ Array Method:
const phoneNumbers = users.map(FP.get('phone'))

```

About to go live shortly in `v1.7.98`
